spring:
  main:
    allow-circular-references: true # Убрать когда springdoc-openapi-ui выкатят версию без бага
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Для сваггера

server:
  port: 8081

s3:
  url: http://localhost:9000
  bucket: images-bucket
  access-key: ${MINIO_ACCESS_KEY:minio_access_key}
  secret-key: ${MINIO_SECRET_KEY:minio_secret_key}
