spring:
  main:
    allow-circular-references: true # Убрать когда springdoc-openapi-ui выкатят версию без бага
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Для сваггера

server:
  port: 8081
